### ISSUE TITLE
Need scene resource

### ISSUE THREAD

**Issue by CGBoy111** [f1shel/Asuna#5]
can't run due to missing scene file, share some resource please

**Comment by f1shel** [comment]
Hi, the usage of scene files is described in detail [here](https://github.com/f1shel/Asuna/wiki/Scene-Description-File-Format). Example scene description files can be found in [Cornell Box](https://github.com/f1shel/Asuna/wiki/Example:-Cornell-Box) and [Asuna-Scenes](https://github.com/f1shel/Asuna-scenes). However, please note that since these files were uploaded a year ago, they may be incompatible with the current version of the program due to potential changes. If you encounter any issues, please let me know.
